/*
 * Generated by MTK SP DrvGen Version 03.13.0  for MT6572_NP. Copyright MediaTek Inc. (C) 2013.
 * Tue May 14 11:48:59 2013
 * Do Not Modify the File.
 */

#define CUST_EINT_MD_LEVEL_SENSITIVE        0
#define CUST_EINT_MD_EDGE_SENSITIVE         1




#define CUST_EINT_MD1_CNT      0


